---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gromit-is-best
  labels:
    app: geo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo
  template:
    metadata:
      labels:
        app: geo
    spec:
      containers:
      - name: hello-server
        image: blux2/hello-server:1.4
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: gromit-configmap
              key: PORT
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gromit-configmap
data:
  PORT: "7777"
