apiVersion: v1
kind: Pod
metadata:
  name: recruit-staging
spec:
  containers:
    - name: likelion-recruit-staging
      image: geooeg/likelion-recruit-staging:latest
      ports:
        - containerPort: 8080
